version: "3.3"

services:
  mongo:
    container_name: mongo
    image: mongo:6.0.1
    restart: on-failure:10
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
