name: Akto Inventory

on:
  push:
    branches: [ flash-inventory-swagger ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate akto endpoints from source code
        working-directory: ./apps/dashboard/web/polaris_web/web/src
        run: |
          grep -r --include "*.js" "api/" . | awk -F"'" '/url:/ {print $2} > ./.github/scripts/polaris-output.txt
      - name: Generate Akto OpenAPI specication file
        working-directory: ./.github/scripts
        env:
            AKTO_DASHBOARD_URL: https://flash.staging.akto.io
            AKTO_API_KEY: ${{secrets.AKTO_API_KEY}}
        run: |
          npm install axios
          node akto-inventory.js
      - name: Archive open_api spec
        uses: actions/upload-artifact@v3
        with:
          name: Akto OpenAPI Specification
          path: ./.github/scripts/akto_open_api.json
